import { PresetLivery } from '../types';

export const PRESET_LIVERIES: PresetLivery[] = [
  {
    id: 'preset_vice_nights',
    name: 'Vice City Nights #88',
    author: 'Vice Customs Studio',
    vehicle: 'infernus',
    state: {
      vehicle: 'infernus',
      primaryColor: '#ff007f',
      secondaryColor: '#00f0ff',
      finish: 'chameleon',
      pearlescentColor: '#00f0ff',
      underglowEnabled: true,
      underglowColor: '#00f0ff',
      underglowBeatPulse: true,
      headlightsOn: true,
      headlightsColor: '#00f0ff',
      doorsOpen: false,
      hoodOpen: false,
      spoilerStyle: 'gt_wing',
      rimStyle: 'cyber_dish',
      rimColor: '#00f0ff',
      windowTint: 'cyan_neon',
      isRainyWeather: true,
      isExhaustFlamesActive: false,
      decals: [
        {
          id: 'preset_d1',
          name: 'Offset Rally Stripe',
          category: 'stripe',
          assetId: 'stripe_asymmetric_rally',
          x: 480,
          y: 512,
          scaleX: 1.2,
          scaleY: 1,
          rotation: 0,
          color: '#00f0ff',
          opacity: 0.9,
          flipX: false,
          flipY: false,
          zIndex: 1,
          visible: true,
        },
        {
          id: 'preset_d2',
          name: '#88 Stencil',
          category: 'stencil',
          assetId: 'stencil_race_number_88',
          x: 512,
          y: 400,
          scaleX: 0.7,
          scaleY: 0.7,
          rotation: 0,
          color: '#ffea00',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 2,
          visible: true,
        },
        {
          id: 'preset_d3',
          name: 'Vice Sunset Palms',
          category: 'flame',
          assetId: 'graphic_vice_palms',
          x: 512,
          y: 650,
          scaleX: 0.8,
          scaleY: 0.8,
          rotation: 0,
          color: '#ffffff',
          opacity: 0.85,
          flipX: false,
          flipY: false,
          zIndex: 3,
          visible: true,
        },
        {
          id: 'preset_d4',
          name: 'PEGASSI Logo',
          category: 'sponsor',
          assetId: 'sponsor_pegassi',
          x: 512,
          y: 250,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          color: '#ffea00',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 4,
          visible: true,
          customText: 'PEGASSI CORSE',
          fontFamily: 'Orbitron'
        },
        {
          id: 'preset_d5',
          name: 'Vice Plate',
          category: 'plate',
          assetId: 'plate_vice_pink',
          x: 512,
          y: 900,
          scaleX: 0.8,
          scaleY: 0.8,
          rotation: 0,
          color: '#ffffff',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 5,
          visible: true,
          plateText: 'VC 1986',
          plateStyle: 'vice_pink'
        }
      ]
    }
  },
  {
    id: 'preset_sprunk_extreme',
    name: 'Sprunk Motorsport',
    author: 'Sprunk Racing Co.',
    vehicle: 'banshee',
    state: {
      vehicle: 'banshee',
      primaryColor: '#102e10',
      secondaryColor: '#39ff14',
      finish: 'metallic',
      pearlescentColor: '#39ff14',
      underglowEnabled: true,
      underglowColor: '#39ff14',
      headlightsOn: true,
      headlightsColor: '#ffffff',
      doorsOpen: false,
      hoodOpen: false,
      spoilerStyle: 'ducktail',
      rimStyle: 'spoke',
      rimColor: '#39ff14',
      windowTint: 'dark_limo',
      isRainyWeather: false,
      isExhaustFlamesActive: false,
      decals: [
        {
          id: 'sprunk_d1',
          name: 'Dual GT Stripes',
          category: 'stripe',
          assetId: 'stripe_dual_center',
          x: 512,
          y: 512,
          scaleX: 1.1,
          scaleY: 1,
          rotation: 0,
          color: '#39ff14',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 1,
          visible: true,
        },
        {
          id: 'sprunk_d2',
          name: 'Sprunk Title',
          category: 'sponsor',
          assetId: 'sponsor_sprunk',
          x: 512,
          y: 350,
          scaleX: 1.2,
          scaleY: 1.2,
          rotation: 0,
          color: '#39ff14',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 2,
          visible: true,
          customText: 'SPRUNK EXTREME',
          fontFamily: 'Impact'
        },
        {
          id: 'sprunk_d3',
          name: 'Checkered Banner',
          category: 'stripe',
          assetId: 'stripe_checkered_side',
          x: 512,
          y: 700,
          scaleX: 1,
          scaleY: 0.8,
          rotation: 0,
          color: '#ffffff',
          opacity: 0.9,
          flipX: false,
          flipY: false,
          zIndex: 3,
          visible: true,
        }
      ]
    }
  },
  {
    id: 'preset_flame_outlaw',
    name: 'Flame Dragster Outlaw',
    author: 'Vice Underground',
    vehicle: 'dominator',
    state: {
      vehicle: 'dominator',
      primaryColor: '#0a0a0d',
      secondaryColor: '#ff5500',
      finish: 'matte',
      pearlescentColor: '#ff0000',
      underglowEnabled: true,
      underglowColor: '#ff0000',
      headlightsOn: true,
      headlightsColor: '#ff5500',
      doorsOpen: false,
      hoodOpen: false,
      spoilerStyle: 'drag',
      rimStyle: 'steelies',
      rimColor: '#ffea00',
      windowTint: 'pink_neon',
      isRainyWeather: true,
      isExhaustFlamesActive: false,
      decals: [
        {
          id: 'flame_d1',
          name: 'Retro Hotrod Flames',
          category: 'flame',
          assetId: 'flame_retro_hotrod',
          x: 512,
          y: 480,
          scaleX: 1.2,
          scaleY: 1.2,
          rotation: 0,
          color: '#ff5500',
          secondaryColor: '#ffea00',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 1,
          visible: true,
        },
        {
          id: 'flame_d2',
          name: 'Skull Wrenches',
          category: 'stencil',
          assetId: 'stencil_skull_wrenches',
          x: 512,
          y: 320,
          scaleX: 0.7,
          scaleY: 0.7,
          rotation: 0,
          color: '#ffffff',
          opacity: 0.95,
          flipX: false,
          flipY: false,
          zIndex: 2,
          visible: true,
        },
        {
          id: 'flame_d3',
          name: 'Bullet Holes',
          category: 'bullet',
          assetId: 'bullet_holes_pack',
          x: 350,
          y: 600,
          scaleX: 0.8,
          scaleY: 0.8,
          rotation: 15,
          color: '#111111',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 3,
          visible: true,
        },
        {
          id: 'flame_d4',
          name: 'Outlaw Plate',
          category: 'plate',
          assetId: 'plate_black_gold',
          x: 512,
          y: 900,
          scaleX: 0.8,
          scaleY: 0.8,
          rotation: 0,
          color: '#ffea00',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 4,
          visible: true,
          plateText: 'V8 BEAST',
          plateStyle: 'black_gold'
        }
      ]
    }
  },
  {
    id: 'preset_cyber_dirtbike',
    name: 'Cyber Demon Offroad',
    author: 'Vice Cybernetics',
    vehicle: 'dirtbike',
    state: {
      vehicle: 'dirtbike',
      primaryColor: '#ffea00',
      secondaryColor: '#9d00ff',
      finish: 'carbon',
      pearlescentColor: '#9d00ff',
      underglowEnabled: true,
      underglowColor: '#9d00ff',
      headlightsOn: true,
      headlightsColor: '#00f0ff',
      doorsOpen: false,
      hoodOpen: false,
      spoilerStyle: 'stock',
      rimStyle: 'gold_wire',
      rimColor: '#ffea00',
      windowTint: 'cyan_neon',
      isRainyWeather: false,
      isExhaustFlamesActive: false,
      decals: [
        {
          id: 'cyber_d1',
          name: 'Cyber Synthwave Wings',
          category: 'flame',
          assetId: 'flame_cyber_neon',
          x: 512,
          y: 450,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          color: '#9d00ff',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 1,
          visible: true,
        },
        {
          id: 'cyber_d2',
          name: 'ATOMIC Tires Sponsor',
          category: 'sponsor',
          assetId: 'sponsor_atomic',
          x: 512,
          y: 280,
          scaleX: 1,
          scaleY: 1,
          rotation: 0,
          color: '#ffea00',
          opacity: 1,
          flipX: false,
          flipY: false,
          zIndex: 2,
          visible: true,
          customText: 'ATOMIC RADIAL',
          fontFamily: 'Orbitron'
        }
      ]
    }
  }
];
